### PR TITLE
closes #21: Fix warnings and add pronto

### LINKED ISSUE #21: Fix warnings and configure pronto

### PR DESCRIPTION
**Pull request by markevich**

### CODE REVIEW

File: lib/co2_offset/converters/plane.ex [hunk 1]
```diff
@@ -9,7 +13,9 @@ defmodule Co2Offset.Converters.Plane do
   # to give 0.36 kg CO2 equivalent per km.
   @co2_per_km 0.18 * 2.0
 
-  def convert_and_structure({co2_amount, acc}) do
+  @spec convert_and_structure({float(), list()}) :: {float(), nonempty_maybe_improper_list()}
+  def convert_and_structure({co2_amount, acc}) when is_float(co2_amount) and is_list(acc) do
+    IO.inspect(123)
```
Comment (markevich) [inline lib/co2_offset/converters/plane.ex]: There should be no calls to IO.inspect/1.

File: lib/co2_offset/converters/plane.ex [hunk 2]
```diff
@@ -18,14 +24,13 @@ defmodule Co2Offset.Converters.Plane do
     }
   end
 
-  @spec convert(float(), :co2_from_km) :: float()
-  def convert(value, :co2_from_km) do
-    (value * @co2_per_km) |> Float.round(4)
+  @spec convert(float(), :co2_from_km | :km_from_co2) :: float()
+  def convert(km, :co2_from_km) when is_float(km) do
+    (km * @co2_per_km) |> Float.round(4)
```
Comment (markevich) [inline lib/co2_offset/converters/plane.ex]: Pipe chain should start with a raw value.

File: lib/co2_offset/converters/plane.ex [hunk 3]
```diff
@@ -18,14 +24,13 @@ defmodule Co2Offset.Converters.Plane do
...
   end
 
-  @spec convert(float(), :km_from_co2) :: float()
-  def convert(value, :km_from_co2) do
-    (value / @co2_per_km) |> Float.round(4)
+  def convert(co2, :km_from_co2) when is_float(co2) do
+    (co2 / @co2_per_km) |> Float.round(4)
```
Comment (markevich) [inline lib/co2_offset/converters/plane.ex]: Pipe chain should start with a raw value.
